FIND_PATH(ODE_ROOT include/ode/ode.h
    PATHS
    $ENV{PATH}
    /usr
    /usr/local
    /opt
)

FIND_PATH(ODE_INCLUDE_DIR ode/ode.h
    PATHS
    ${ODE_ROOT}/include
)

FIND_LIBRARY(ODE_SINGLE_LIBRARY
    NAMES ode_single
    PATHS
    ${ODE_ROOT}/lib
)

FIND_LIBRARY(ODE_SINGLE_LIBRARY_DEBUG
    NAMES ode_singled
    PATHS
    ${ODE_ROOT}/lib
)

FIND_LIBRARY(ODE_DOUBLE_LIBRARY
    NAMES ode_double
    PATHS
    ${ODE_ROOT}/lib
)

FIND_LIBRARY(ODE_DOUBLE_LIBRARY_DEBUG
    NAMES ode_doubled
    PATHS
    ${ODE_ROOT}/lib
)

SET(ODE_FOUND "NO")
IF(ODE_INCLUDE_DIR AND ODE_SINGLE_LIBRARY)
    SET(ODE_FOUND "YES")
ENDIF(ODE_INCLUDE_DIR AND ODE_SINGLE_LIBRARY)

MARK_AS_ADVANCED(ODE_INCLUDE_DIR ODE_SINGLE_LIBRARY ODE_DOUBLE_LIBRARY
                 ODE_SINGLE_LIBRARY_DEBUG ODE_DOUBLE_LIBRARY_DEBUG
)
